### ISSUE TITLE
Representation metatada and 204 No Content

### ISSUE THREAD

**Issue by ioggstream** [httpwg/http-core#255]
My understanding of [Representation Metadata semantics-6.2](https://tools.ietf.org/html/draft-ietf-httpbis-semantics-05#section-6.2)
is that it is perfectly legal to use representation-metadata in responses without payload
unless explicitly forbidden (eg. 204+Content-Length).

An example is 

```
Request:

  HEAD /books/123 HTTP/1.1
  
Response:
 
  HTTP/1.1 200 Ok
  Content-Type: application/json
  Content-Encoding: gzip
  Content-Length: 1024
```

I think that's valid for PUT + 204.
Is that ok? Is it worth expliciting that in the specs?

eg.

```
Request:

  PUT /books/123 HTTP/1.1
  Accept: application/json
  Accept-Encoding: gzip

  {"title": "new"}

Response:
 
  HTTP/1.1 204 No Content
  Content-Type: application/json 
  Content-Encoding: gzip

```
